version: 2.1

jobs:
  extract_sha:
    docker:
      - image: cimg/base:stable  # Base image with Git pre-installed
    steps:
      - checkout  # Check out the repository
      - run:
          name: "Add SSH Host to Known Hosts"
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          name: "Fetch Remote Branches"
          command: git fetch --all
      - run:
          name: "Identify Merged Branch and Use Source SHA"
          command: |
            # Get the merge commit SHA (most recent merge commit)
            MERGE_COMMIT_SHA=$(git log --merges -n 1 --pretty=format:"%H")
            echo "Merge Commit SHA: $MERGE_COMMIT_SHA"

            # Get parent commits of the merge commit
            PARENTS=$(git log -n 1 --pretty=%P $MERGE_COMMIT_SHA)
            FIRST_PARENT=$(echo $PARENTS | awk '{print $1}')
            SECOND_PARENT=$(echo $PARENTS | awk '{print $2}')

            echo "First Parent (Target Branch): $FIRST_PARENT"
            echo "Second Parent (Source Branch): $SECOND_PARENT"

            # The correct SHA for the promotion is the SECOND_PARENT
            PROMOTION_SHA=$SECOND_PARENT
            echo "Promoting Image for SHA: $PROMOTION_SHA"

            # Create a shortened build tag from the PROMOTION_SHA
            export BUILD_TAG="${PROMOTION_SHA:0:7}"
            echo "export BUILD_TAG=$BUILD_TAG" >> $BASH_ENV
            printf "${BUILD_TAG}" > build_tag.txt
            echo "Build Tag: $BUILD_TAG"
      - run:
          name: "Verify Build Tag"
          command: |
            source $BASH_ENV
            echo "Verified Build Tag: $BUILD_TAG"

workflows:
  version: 2
  test_workflow:
    jobs:
      - extract_sha
