version: 2.1

jobs:
  extract_sha:
    docker:
      - image: cimg/base:stable  # Base image with Git pre-installed
    steps:
      - checkout  # Check out the repository
      - run:
          name: "Create Shortened Build Tag"
          command: |
            # Convert the current SHA (CIRCLE_SHA1) to a shortened build tag
            export BUILD_TAG="${CIRCLE_SHA1:0:7}"
            echo "export BUILD_TAG=$BUILD_TAG" >> $BASH_ENV
            printf "${BUILD_TAG}" > build_tag.txt
            echo "Build Tag: $BUILD_TAG"
      - run:
          name: "Fetch Remote Branches"
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            git fetch --all
            SECOND_PARENT=$(git log -n 1 --pretty=%P $(git log --merges -n 1 --pretty=%H) | awk '{print $2}')
            export EXTRACTED_BUILD_TAG="${SECOND_PARENT:0:7}"
            echo "Extracted Build Tag: $EXTRACTED_BUILD_TAG"
      

            


workflows:
  version: 2
  test_workflow:
    jobs:
      - extract_sha